# Generated by Django 5.1.2 on 2024-10-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=300, verbose_name="Full name"),
        ),
    ]
